# Generated by Django 5.1.5 on 2025-01-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='lesson_history',
        ),
        migrations.AddField(
            model_name='member',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='자기소개'),
        ),
        migrations.AlterField(
            model_name='fitonuser',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='fitonuser',
            name='role',
            field=models.CharField(blank=True, choices=[('member', '수강생'), ('instructor', '강사'), ('centerowner', '센터장')], max_length=20, null=True, verbose_name='역할'),
        ),
    ]
