# Generated by Django 5.1.5 on 2025-01-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_member_lesson_history_member_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitonuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', '남자'), ('Female', '여자'), ('None', '비공개')], max_length=6, null=True, verbose_name='성별'),
        ),
    ]
