# Generated by Django 5.1.3 on 2025-02-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_fitonuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitonuser',
            name='role',
            field=models.CharField(blank=True, choices=[('member', '수강생'), ('instructor', '강사'), ('centerowner', '센터장')], max_length=20, null=True, verbose_name='역할'),
        ),
    ]
