services:
  minio:
    image: minio/minio
    ports:
      - "9002:9000"
      - "9003:9001" 
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --address ":9002" --console-address ":9003"
    restart: always

volumes:
  minio_data:
