# Generated by Django 5.1.5 on 2025-01-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='편의시설 이름')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='운동 이름')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='가격(원)')),
                ('duration', models.IntegerField(verbose_name='기간(일)')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='시작 날짜')),
                ('end_date', models.DateField(verbose_name='종료 날짜')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
            ],
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='센터 이름')),
                ('location', models.CharField(max_length=255, verbose_name='센터 위치')),
                ('image', models.ImageField(blank=True, null=True, upload_to='center_images/', verbose_name='센터 이미지')),
                ('amenity', models.ManyToManyField(to='centers.amenity', verbose_name='편의시설')),
            ],
        ),
    ]
