# Generated by Django 5.1.5 on 2025-01-24 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centers', to='users.centerowner', verbose_name='센터장'),
        ),
        migrations.AddField(
            model_name='center',
            name='exercise',
            field=models.ManyToManyField(to='centers.exercise', verbose_name='운동 종목'),
        ),
        migrations.AddField(
            model_name='membership',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_memberships', to='centers.center', verbose_name='센터'),
        ),
        migrations.AddField(
            model_name='membershipowner',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_owners', to='centers.center', verbose_name='센터'),
        ),
        migrations.AddField(
            model_name='membershipowner',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_owners', to='users.member', verbose_name='수강생'),
        ),
    ]
