# Generated by Django 5.1.5 on 2025-02-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='편의시설 이름'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='운동 이름'),
        ),
    ]
