services:
  nextjs:
    build: .
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    networks:
      - next-network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
    depends_on:
      - nextjs
    networks:
      - next-network

networks:
  next-network:
    driver: bridge
