services:
  next-dev:
    build:
      context: .  # 현재 디렉토리(frontend/nextjs) 기준
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app       # 현재 폴더 전체 매핑
      - /app/node_modules
    env_file:
      - .env.local   # 현재 폴더의 파일 직접 지정

  next-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    restart: unless-stopped
