version: '3.8'

services:
  next-dev:
    build:
      context: ./frontend/nextjs  # 중요: nextjs 폴더 경로
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/nextjs:/app
      - /app/node_modules
    env_file:
      - ./frontend/nextjs/.env.local

  next-prod:
    build:
      context: ./frontend/nextjs
      dockerfile: Dockerfile
      target: prod
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/nextjs/.env.production
    restart: unless-stopped
