services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - API_URL=${API_URL}
      - NEXT_PUBLIC_MINIO_ENDPOINT=${NEXT_PUBLIC_MINIO_ENDPOINT}
      - NEXT_PUBLIC_MINIO_PORT=${NEXT_PUBLIC_MINIO_PORT}
      - NEXT_PUBLIC_MINIO_BUCKET_NAME=${NEXT_PUBLIC_MINIO_BUCKET_NAME}
      - NODE_ENV=production
    networks:
      - next-network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.next:/app/.next
    depends_on:
      - nextjs
    networks:
      - next-network

networks:
  next-network:
    driver: bridge
