# Generated by Django 5.1.5 on 2025-01-24 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('attended', '참석'), ('no-show', '미 참석')], default='no-show', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmed', '예약 확정'), ('waiting', '예약 대기'), ('canceled', '예약 취소')], default='confirmed', max_length=10)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('cancel_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompletedLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='완료 일시')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='수강생 피드백')),
                ('lesson_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson_schedule', verbose_name='수업 스케줄')),
            ],
        ),
    ]
