# Generated by Django 5.1.5 on 2025-01-24 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_lesson', models.DateTimeField(verbose_name='수업 진행 일시')),
                ('reservation_permission', models.DateTimeField(blank=True, null=True, verbose_name='예약 가능 시간')),
                ('cancellation_permission', models.DateTimeField(blank=True, null=True, verbose_name='예약 취소 날짜')),
                ('max_member', models.IntegerField(verbose_name='최대 인원')),
            ],
        ),
        migrations.CreateModel(
            name='LessonTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='가격(원)')),
            ],
        ),
        migrations.CreateModel(
            name='LessonTicketOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='수업권 개수')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='사용한 수업권 횟수')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='제목')),
                ('content', models.TextField(blank=True, null=True, verbose_name='수업 내용')),
                ('location', models.TextField(max_length=255, verbose_name='수업 장소')),
                ('duration', models.PositiveIntegerField(default=60, verbose_name='진행 시간(분)')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='centers.center', verbose_name='진행 센터')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='centers.exercise', verbose_name='운동 종목')),
            ],
        ),
    ]
